.data
bgstart location <0, 0, 700, 600>
board   location <50, 50, 144, 142>
window  location <850, 150, 720, 660>
client  location <0, 0, 700, 600>

ROUND_NUMBER dd 4
EACH_ROUND_ENEMY_NUMBER dd 3,4,5,6
EACH_ROUND_ENEMY_TYPE dd 0,0,0,
                         0,0,0,0,
                         0,0,0,0,0,
                         0,0,0,0,0,0
ENEMY_LIFE_0 = 40
ENEMY_MONEY_0 = 10

TOWERPOSITION dd 248, 312, 246, 365